Configuration:
    pattern: /configuration/
    defaults: { _controller: OWMBundle:Configuration:index }
Configuration_voir:
    pattern: /configuration/voir/
    defaults: { _controller: OWMBundle:Configuration:voir }
Configuration_modifier:
    pattern: /configuration/modifier/
    defaults: { _controller: OWMBundle:Configuration:modifier }
Clients:
    pattern: /clients/
    defaults: { _controller: OWMBundle:Clients:index }
Clients_voir:
    pattern: /clients/voir/
    defaults: { _controller: OWMBundle:Clients:voir }
Clients_modifier:
    pattern: /clients/modifier/
    defaults: { _controller: OWMBundle:Clients:modifier }
Clients_creer:
    pattern: /clients/creer/
    defaults: { _controller: OWMBundle:Clients:creer }
Paquets:
    pattern: /paquets/
    defaults: { _controller: OWMBundle:Paquets:index }
Paquets_voir:
    pattern: /paquets/voir/
    defaults: { _controller: OWMBundle:Paquets:voir }
Paquets_modifier:
    pattern: /paquets/modifier/
    defaults: { _controller: OWMBundle:Paquets:modifier }
Paquets_details:
    pattern: /paquets/detail/{pkg}/
    defaults: { _controller: OWMBundle:Paquets:detail }
