homepage:
    pattern: /
    defaults: { _controller: OWMBundle:Welcome:index }
Configuration:
    pattern: /configuration/
    defaults: { _controller: OWMBundle:Configuration:index }
Configuration_voir:
    pattern: /configuration/voir/
    defaults: { _controller: OWMBundle:Configuration:voir }
Configuration_modifier:
    pattern: /configuration/modifier/
    defaults: { _controller: OWMBundle:Configuration:modifier }
Clients:
    pattern: /clients/
    defaults: { _controller: OWMBundle:Clients:index }
Clients_process:
    pattern: /clients/process/
    defaults: { _controller: OWMBundle:Clients:process }
Clients_voir:
    pattern: /clients/voir/
    defaults: { _controller: OWMBundle:Clients:voir }
Clients_modifier:
    pattern: /clients/modifier/
    defaults: { _controller: OWMBundle:Clients:modifier }
Clients_detail:
    pattern: /clients/detail/{client}/
    defaults: { _controller: OWMBundle:Clients:detail }
Clients_creer:
    pattern: /clients/creer/
    defaults: { _controller: OWMBundle:Clients:creer }
Clients_supprimer:
    pattern: /clients/supprimer/{client}/
    defaults: { _controller: OWMBundle:Clients:supprimer }
Paquets:
    pattern: /paquets/
    defaults: { _controller: OWMBundle:Paquets:index }
Paquets_voir:
    pattern: /paquets/voir/
    defaults: { _controller: OWMBundle:Paquets:voir }
Paquets_modifier:
    pattern: /paquets/modifier/
    defaults: { _controller: OWMBundle:Paquets:modifier }
Paquets_details:
    pattern: /paquets/detail/{pkg}/
    defaults: { _controller: OWMBundle:Paquets:detail }
Paquets_creer:
    pattern: /paquets/creer/
    defaults: { _controller: OWMBundle:Paquets:creer }
Paquets_creer_localboot:
    pattern: /paquets/creer/localboot/
    defaults: { _controller: OWMBundle:Paquets:creerLocalBoot }
Paquets_creer_netboot:
    pattern: /paquets/creer/netboot/
    defaults: { _controller: OWMBundle:Paquets:creerNetBoot }
Paquets_compiler:
    pattern: /paquets/compiler/
    defaults: { _controller: OWMBundle:Paquets:compiler }
Paquets_installer:
    pattern: /paquets/installer/
    defaults: { _controller: OWMBundle:Paquets:installer }
Paquets_desinstaller:
    pattern: /paquets/desinstaller/
    defaults: { _controller: OWMBundle:Paquets:desinstaller }
Backup: 
    pattern: /backups/
    defaults: { _controller: OWMBundle:Backups:index }

