OWMBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: OWMBundle:Default:index }
Configuration:
    pattern: /configuration
    defaults: { _controller: OWMBundle:Configuration:voir }
