OWMBundle:
    resource: "@OWMBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
